#!/bin/sh

### BEGIN INIT INFO
# Provides:          monsti
# Required-Start:    $local_fs $remote_fs $network
# Required-Stop:     $local_fs $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts monsti
# Description:       starts monsti using start-stop-daemon
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin
DAEMON=/usr/bin/monsti-daemon
DAEMON_OPTS="-syslog /etc/monsti"
NAME=monsti
DESC=monsti
USER=monsti
GROUP=monsti

test -x $DAEMON || exit 0

set -e

. /lib/lsb/init-functions

case "$1" in
  start)
    echo -n "Starting $DESC: "
    start-stop-daemon --start --quiet --pidfile /var/run/$NAME.pid \
        --chuid $USER:$GROUP \
        --background --make-pidfile --exec $DAEMON -- $DAEMON_OPTS || true
    echo "$NAME."
    ;;

  stop)
    echo -n "Stopping $DESC: "
    start-stop-daemon --stop --quiet --pidfile /var/run/$NAME.pid \
        --user $USER --exec $DAEMON || true
    echo "$NAME."
    ;;

  restart|force-reload)
    echo -n "Restarting $DESC: "
    start-stop-daemon --stop --quiet --pidfile \
        --user $USER /var/run/$NAME.pid --exec $DAEMON || true
    sleep 1
    start-stop-daemon --start --quiet --pidfile --chuid $USER:$GROUP \
        /var/run/$NAME.pid --make-pidfile --background --exec $DAEMON -- $DAEMON_OPTS || true
    echo "$NAME."
    ;;

  *)
    echo "Usage: $NAME {start|stop|restart|force-reload}" >&2
    exit 1
    ;;
esac

exit 0
