= Monsti Developer Manual
:imagesdir: static/img
:data-uri:
:icons:
:toc:
:homepage: http://www.monsti.org

== Bulding Monsti

=== Get Monsti

Get the latest sources: +
https://gitorious.org/monsti/monsti/

=== Dependencies

- make
- C compiler, pkg-config
- Git, Bazaar, Mercurial (to fetch Go packages)
- MagickCore library and development files
- Latest Go compiler and tools


=== Build

`$ make`


=== Tests

`$ make test`

For Selenium tests, have a look at `tests/README`

=== Run

`$ go/bin/monsti-daemon <configuration directory>`

To run the example site, go to the example site directory (example/)
and run the start script: +
`$ ./start.sh` +
Monsti will be listening on http://localhost:8080

=== Deployment

Create packages to deploy (if you like):

tar: +
`$ make dist`

Debian archive (using https://github.com/jordansissel/fpm[fpm]): +
`$ make dist-deb`

=== Documentation

Makefile rule: `doc`

You will need following tools to build the documentation:

- http://www.methods.co.nz/asciidoc/[AsciiDoc]
- http://www.gnu.org/software/src-highlite/[source-highlight]

== Node types

=== Modifying node types

You have to be careful if you want to modify node types which have
existing instances in one of your Monsti sites.

WARNING: Keep a backup of the sites' node data before changing node
types!

Never change the namespace or id, as this basically removes the old
and creates a new node type. If you really want to do this, you have
to change the namespace or type id of the existing instances as well.

It's no problem to change the name of the node types (or fields) or
add or remove translations of them.

If one of the field ids is changed, it's the same as removing the old
and creating a new field.

You may add and remove new fields at any time, the node type instances
will get fixed the next time you save the instance. Existing data of
removed fields will get purged.

Don't change the types of the fields without changing the id if you're
not sure if the field types are compatible. This will result in
undefined behaviour. If you want to keep the id you could remove the
old field data before adding the new field.

=== Configuration

==== Directives

namespace (string)::
  Sets the namespace for configured node types.

nodetypes ([...])::
  List of node types to be configured.

nodetypes > id (string)::
  ID of the configured node type (without namespace, this will be set
  using the `namespace` directive).

nodetypes > name ({language-code -> string})::
  The name of the node type as shown in the web interface, specified
  as a translation map.

nodetypes > addable_to ([string])::
  Per default, nodes may be added to any other node. This behaviour
  can be overwritten for one node type with the `addable_to`
  option. Nodes of this type may only be added to nodes of the
  specified types. If you specify an empty array, the node can't be
  added to any other node.
  It's still possible to add nodes to any other node by directly
  manipulating the node data on the file system. This option merely
  affects the web interface.

nodetypes > fields ([...])::
  List of the node type's fields.

nodetypes > fields > id (string)::
  ID of the node type field (without namespace, this will be set using
  the `namespace` directive).

nodetypes > fields > name ({language-code -> string})::
  The name of the node type field as shown in the web interface,
  specified as a translation map.

nodetypes > fields > type (string})::
  The type of the field.

== Translating Monsti

Monsti uses https://www.gnu.org/software/gettext/[gettext] to
translate it's web interface. An exception are node type names and
descriptions, which are translated in their configuration files.

You can find the gettext files below `locale/` in the project's root
directory. Also have a look at the `locales` rule in the Makefile.

.Tips for beginners
[TIP]
Use the http://littlesvr.ca/ostd/translatepot.php[Open Source
Translation Database] if you want to create a new basic
translation. After that, you can use a user friendly tool like
https://wiki.gnome.org/Apps/Gtranslator[Gtranslator] to tweak the
translation.
You will need the file `locale/monsti-daemon.pot` and
produce a file `monsti-daemon.po`, wich will be placed into
`locale/<language_code>/LC_MESSAGES/`. You will find any existing
translations in this directory.
To help improving an existing translation, get in touch with the
author(s) of the translation (the authors are noted in the `.po` files).