= Monsti Manual
:imagesdir: static/img
:data-uri:
:icons:
:toc:
:homepage: http://www.monsti.org

== Bulding Monsti

=== Get Monsti

Get the latest sources: +
https://gitorious.org/monsti/monsti/

=== Dependencies

- make
- C compiler
- Git, Bazaar, Mercurial (to fetch Go packages)
- Latest Go compiler and tools


=== Build

`$ make`


=== Tests

`$ make test`

For Selenium tests, have a look at `tests/README`

=== Run

`$ go/bin/monsti-daemon <configuration directory>`

To run the example site, go to the example site directory (example/)
and run the start script: +
`$ ./start.sh` +
Monsti will be listening on http://localhost:8080

=== Deployment

Create packages to deploy (if you like):

tar: +
`$ make dist`

Debian archive (using https://github.com/jordansissel/fpm[fpm]): +
`$ make dist-deb`

=== Documentation

Makefile rule: `doc`

You will need following tools to build the documentation:

- http://www.methods.co.nz/asciidoc/[AsciiDoc]
- http://www.gnu.org/software/src-highlite/[source-highlight]


== Architecture [[sec-architecture]]

(This section is somewhat outdated with regard to the existing modules
and services. Currently, there is only one module, the master daemon
which implements the main services.)

Monsti consists of modules that provide services like database access
or nodes processing. Modules use other modules services via RPC
communication through UNIX domain sockets. The master daemon controls
and starts the modules. Currently, Monsti differentiates between these
services: service information, node processing, database, mail sending
and user authentication.

The info service is implemented by the master daemon and provides
information about known modules and their services. Modules which
provide the node service process incoming requests for specific node
types. Modules with the database service provide access to the
websites' node data.

A module may provide more than one service. Each module creates a UNIX
domain socket to which other modules can connect to use the module's
services.

=== monsti-daemon

Monsti-daemon is the master daemon of Monsti. It provides the info
service and is started by the user. The master daemon starts all the
other modules. Each module registers its services using the master
daemon's info Service. If a module needs some specific service it uses
the info service to get the path to a UNIX domain socket which belongs
to a module which provides this service.

It also listens for incoming HTTP requests and uses other services to
process the requests.

Beside that, it also provides access to the node data. It uses
ordinary files and directories to save the node data. Each node is
represented by a directory containing at least one `node.json` file,
possibly node type specific data, and subdirectories belonging to
child nodes. The `node.json` file contains common node attributes like
the title and the node type, and also node type specific field data.

== Nodes

=== Embedding

You may embed nodes into other nodes. This is useful if for example
you want to include in a `core.Document` node a list of recently
changed nodes which is implemented by another node type
`foo.RecentlyChangedList`.

To do this, create a (possibly hidden) node of type
`foo.RecentlyChangedList` and embed it into the document node by
setting the embed option in the node's `Embed` attribute. Each embed
has an id and an URI. The id is used to access the embeded content,
the URI is the path to the embedded node, including any arguments.

You may access the embedded content in templates with
`.Embed.<ID>`. For the above example, you have to overwrite the
`core.Document` template for this node to actually add the embedded
content. See the section about template overwrites how to do this.

As always, have a look at the example site (`Nodes > Embedding`).

=== Query parameters

Query parameters of the requsted node are not passed directly to the
embedded node. Instead, any parameters specified in the embed option
URI are passed. At some point, it will be possible to access the
requested node's parameter.

== Node types

=== Core Node Types

==== Image

The Image node type allows you to upload images to your Monsti
site. As the File node type, the raw content (i.e. the image itself)
can be accessed via the node's path without trailing slash.

.Example for raw image access
If the node's path is `/foo/my_image.jpeg/`, then the raw image data
can be access via `/foo/my_image.jpeg`.


=== Modifying node types

You have to be careful if you want to modify node types which have
existing instances in one of your Monsti sites.

WARNING: Keep a backup of the sites' node data before changing node
types!

Never change the namespace or id, as this basically removes the old
and creates a new node type. If you really want to do this, you have
to change the namespace or type id of the existing instances as well.

It's no problem to change the name of the node types (or fields) or
add or remove translations of them.

If one of the field ids is changed, it's the same as removing the old
and creating a new field.

You may add and remove new fields at any time, the node type instances
will get fixed the next time you save the instance. Existing data of
removed fields will get purged.

Don't change the types of the fields without changing the id if you're
not sure if the field types are compatible. This will result in
undefined behaviour. If you want to keep the id you could remove the
old field data before adding the new field.


=== Local fields

Local fields are fields that are only configured for one node, not a
whole node type. Local fields can be specified in the node's
`node.json` file. Have a look at the `LocalFields` attribute and the
example.


== Translating Monsti

Monsti uses https://www.gnu.org/software/gettext/[gettext] to
translate it's web interface. An exception are node type names and
descriptions, which are translated in their configuration files.

You can find the gettext files below `locale/` in the project's root
directory. Also have a look at the `locales` rule in the Makefile.

.Tips for beginners
[TIP]
Use the http://littlesvr.ca/ostd/translatepot.php[Open Source
Translation Database] if you want to create a new basic
translation. After that, you can use a user friendly tool like
https://wiki.gnome.org/Apps/Gtranslator[Gtranslator] to tweak the
translation.
You will need the file `locale/monsti-daemon.pot` and
produce a file `monsti-daemon.po`, wich will be placed into
`locale/<language_code>/LC_MESSAGES/`. You will find any existing
translations in this directory.
To help improving an existing translation, get in touch with the
author(s) of the translation (the authors are noted in the `.po` files).

== Modules

Modules allow to add new functionality or alter Monsti's
behaviour. See <<sec-architecture, the section about Monsti's architecture>> 
for a detailed description.

=== Writing modules

Have a look at the documented example module
`monsti-example-module`. It shows how to setup a module and call Monsti's API.

== Configuration

=== `monsti.yaml`

This file contains common Monsti settings used by all modules.

----
include::../example/config/monsti.yaml[]
----

=== `daemon.yaml`

The master daemon's (`monsti-daemon`) configuration.

----
include::../example/config/daemon.yaml[]
----

== Templates

Monsti uses Go's
link:http://golang.org/pkg/html/template/[`html/template`]
package. Beside a global template directory that is used by all sites,
you may configure site local template directories. The template
directories contain templates and include files.

=== Include Files

Include files specify for a directory subtree or individual templates,
which other templates may be called inside the templates. Include
files contain one template name per line. Specify callable templates
for an individual template named `foo.html` in a file named
`foo.include` in the same directory. To include callable templates for
all templates of a directory tree, add the names of the templates to a
file named `include` at the root of the tree.

=== Template Overwrites

You can overwrite templates for individual nodes by setting the
corresponding option in the node's `node.json` file. Have a look at
the `service.Node` API documentation or the examples for more
information.

==== Automatic resizing

Monsti features automatic resizing of images. First, you have to
register your allowed image sizes in
`<config_dir>/sites/<your_site>/image.json`.

.Example for image sizes "thumbnail" (200x100) and "icon" (20x20)
[source,javascript]
----
{
  "sizes": {
    "thumbnail": { "Width":200, "Height":100 },
    "icon": { "Width":20, "Height":20 },
  }
}
----

To access these sizes, add `?size=<size_name>` to the image URL,
e.g. `/foo/my_image.jpeg?size=thumbnail`.

Monsti will generate the specified size if it has not been generated
before and saves it in the node's directory.
