= Monsti Manual
:imagesdir: static/img
:data-uri:
:icons:
:toc:
:homepage: http://www.monsti.org

== Bulding Monsti

=== Get Monsti

Get the latest sources: +
https://gitorious.org/monsti/monsti/

=== Dependencies

- make
- C compiler
- Git, Bazaar, Mercurial (to fetch Go packages)
- Go 1.3 or later
- wget


=== Build

To fetch the dependencies and compile the sources, run the Makefile in
the main directory using the `make` command:

`$ make`

=== Tests

To start all the tests (excluding the Selenium tests, see below for
that), run the Makefile with the `test` target:

`$ make test`

For Selenium tests (browser/integration tests), have a look at
`tests/README`.

=== Run

In the main directory, run the following command to start Monsti.

`$ go/bin/monsti-daemon <configuration directory>`

To run the example site, go to the example site directory (`example/`)
and run the start script:

`$ ./start.sh`

Monsti will be listening on http://localhost:8080

=== Deployment

To create a tar archive containing all needed resources, run the
following command in the main directory:

`$ make dist`

Copy the archive (`dist/monsti-$VERSION.tar.gz`) to your server and
unpack it, e.g. in `/opt`. A startup script (`start.sh`) is included
to start Monsti. The user running Monsti must have read-write access
to the `data` and `run` directories and read access to all other
unpacked directories. To start Monsti on boot, write an init script
(you'll find an example init script for Debian in the `example`
directory) or use a software like
http://supervisord.org/[supervisord]. To use syslog, run Monsti with
the `-syslog` option.

==== Debian

If you use Debian, you might create a simple `deb` package using
https://github.com/jordansissel/fpm[fpm]. Use the following command in
the main directory:

`$ make dist-deb`

Install the package (`dist/monsti-$VERSION.deb`) and run Monsti with
`monsti-daemon /etc/monsti`.

=== Documentation

Makefile rule: `doc`

You will need following tools to build the documentation:

- http://www.methods.co.nz/asciidoc/[AsciiDoc]
- http://www.gnu.org/software/src-highlite/[source-highlight]


== Typical usage

- Copy the example site's data to a new directory in the data
  directory and name it matching the hostname of the new site.
- Alter the templates according to you needs.
- Create a new module to implement new functionality and custom node
  types.

== Architecture [[sec-architecture]]

Monsti's master daemon provides the core functionality of Monsti. It
serves incoming HTTP requests and provides a RPC interface over a UNIX
domain socket.

Modules extend or alter the core functionality. They are separate
processes that communicate to the master daemon (and possibly each
other) using the RPC interface. The master daemon is usually
configured to automatically start and shutdown the module processes.

== Nodes

=== Embedding

You may embed nodes into other nodes. This is useful if for example
you want to include in a `core.Document` node a list of recently
changed nodes which is implemented by another node type
`foo.RecentlyChangedList`.

To do this, create a (possibly hidden) node of type
`foo.RecentlyChangedList` and embed it into the document node by
setting the embed option in the node's `Embed` attribute. Each embed
has an id and an URI. The id is used to access the embeded content,
the URI is the path to the embedded node, including any arguments.

You may access the embedded content in templates with
`.Embed.<ID>`. For the above example, you have to overwrite the
`core.Document` template for this node to actually add the embedded
content. See the section about template overwrites how to do this.

As always, have a look at the example site (`Nodes > Embedding`).

=== Query parameters

Query parameters of the requsted node are not passed directly to the
embedded node. Instead, any parameters specified in the embed option
URI are passed. At some point, it will be possible to access the
requested node's parameter.

== Field types

=== Combined

Combined fields allow to group multiple fields of arbitrary types.

=== DateTime

The DateTime field stores a point in time. Views and form inputs will
honour the site's time zone (i.e. the user will see and enter times in
the configured time zone (`core.Timezone` setting)).

=== Map

Map fields map string keys to fields of a configurable type.

== Node types

=== Core Node Types

==== core.ContactForm

The contact form node type allows to realize contact forms with custom
fields on your website. Currently, fields can only be configured
directly in the node's json file. Have a look at the contact form in
the example.

For backward compatibility, contact forms without configured form
fields will be provided with some default fields.

==== core.Path

The Path node type is not written to the database. It will be returned
by `monsti.GetChildren` and `monsti.GetNode` to represent a
directory that is not a regular node but may contain children.

==== core.Image

The Image node type allows you to upload images to your Monsti
site. As the File node type, the raw content (i.e. the image itself)
can be accessed via the node's path without trailing slash.

.Example for raw image access
If the node's path is `/foo/my_image.jpeg/`, then the raw image data
can be access via `/foo/my_image.jpeg`.


==== core.Vocabulary (Experimental)

The Vocabulary node type defines a taxonomy. Have a look at
<<taxonomy>>.

===== Automatic resizing

Monsti features automatic resizing of images. First, you have to
configure your allowed image sizes. Have a look at the
`core.ImageStyles` setting of the example site.

To access these sizes, add `?size=<size_name>` to the image URL,
e.g. `/foo/my_image.jpeg?size=thumbnail`.

Resized images will be cached.

=== Modifying node types

You have to be careful if you want to modify node types which have
existing instances in one of your Monsti sites.

WARNING: Keep a backup of the sites' node data before changing node
types!

Never change the namespace or id, as this basically removes the old
and creates a new node type. If you really want to do this, you have
to change the namespace or type id of the existing instances as well.

It's no problem to change the name of the node types (or fields) or
add or remove translations of them.

If one of the field ids is changed, it's the same as removing the old
and creating a new field.

You may add and remove new fields at any time, the node type instances
will get fixed the next time you save the instance. Existing data of
removed fields will get purged.

Don't change the types of the fields without changing the id if you're
not sure if the field types are compatible. This will result in
undefined behaviour. If you want to keep the id you could remove the
old field data before adding the new field.

== Translating Monsti

Monsti uses https://www.gnu.org/software/gettext/[gettext] to
translate it's web interface. An exception are node type names and
descriptions, which are translated in their configuration files.

You can find the gettext files below `locale/` in the project's root
directory. Also have a look at the `locales` rule in the Makefile.

.Tips for beginners
[TIP]
Use the http://littlesvr.ca/ostd/translatepot.php[Open Source
Translation Database] if you want to create a new basic
translation. After that, you can use a user friendly tool like
https://wiki.gnome.org/Apps/Gtranslator[Gtranslator] to tweak the
translation.
You will need the file `locale/monsti-daemon.pot` and
produce a file `monsti-daemon.po`, wich will be placed into
`locale/<language_code>/LC_MESSAGES/`. You will find any existing
translations in this directory.
To help improving an existing translation, get in touch with the
author(s) of the translation (the authors are noted in the `.po` files).

== Navigations

The `core.Navigation` setting currently allows to configure the main
navigation (no GUI yet). The corresponding map key is `core.Main`.

[[taxonomy]]
== Taxonomy (Experimental)

There is really basic support for taxonomies in Monsti. You have to create
a node of type `core.Vocabulary` to define the taxonomy and its terms
(unless they are free form, i.e. tags, in which case you still have to
create an empty vocabulary).

Terms can be assigned to nodes using the `core.Categories` field. The
field is a map from vocabulary path to terms.

The API's `taxonomy` package contains functions to query for nodes
belonging to some term.

== Modules

Modules allow to add new functionality or alter Monsti's
behaviour. See <<sec-architecture, the section about Monsti's architecture>> 
for a detailed description.

=== Writing modules

Have a look at the documented example module
`monsti-example-module`. It shows how to setup a module and call
Monsti's API, including use of signals.

=== Signals

Monsti includes a signal mechanism to alter functionality. For
example, when a node gets visited and rendered, the `RenderNode`
signal will be called which can be used for various tasks as to add
content, process form submits, or redirect to another node. Have a
look at the example how to use signals and refer to the service API
documentation for a list of available signals.

== Configuration

=== `monsti.yaml`

This file contains common Monsti settings used by all modules.

----
include::../example/config/monsti.yaml[]
----

=== `daemon.yaml`

The master daemon's (`monsti-daemon`) configuration.

----
include::../example/config/daemon.yaml[]
----

== Caching

Monsti uses a dependency based caching system. Any byte data can be
cached, e.g. whole pages, page content, thumbnails, queries, and
calculations. Each cached data may depend on other (possibly cached)
data. For example, the cached output of a node request depends on the
fields of the node, the navigation content, and settings like the site
title. If one of these dependencies get changed (dirty), all caches
that depend on these get recursively cleared.

Caches are stored in the sites' data directories. To clear the cache,
simply remove the cache directory. You may disable caching per site
using the `core.CacheDisabled` setting (you'll also have to clear the
cache directory to remove old cached data). Disable caching only for
development purposes.

Have a look at the `ToCache`, `FromCache`, and `MarkDep` service
methods.

== Templates

Monsti uses Go's
link:http://golang.org/pkg/html/template/[`html/template`]
package. Beside a global template directory that is used by all sites,
you may configure site local template directories. The template
directories contain templates and include files.

=== Include Files

Include files specify for a directory subtree or individual templates,
which other templates may be called inside the templates. Include
files contain one template name per line. Specify callable templates
for an individual template named `foo.html` in a file named
`foo.include` in the same directory. To include callable templates for
all templates of a directory tree, add the names of the templates to a
file named `include` at the root of the tree.